### PR TITLE
wip: framer motion

### PR DESCRIPTION
**Pull request by Richi2293**
**(Don't merge at the moment)**

----------
Sorry for the mistake, this is the same PR of this [old PR](https://github.com/anubra266/choc-autocomplete/pull/178).

Now the installation of the library seems to work, but before merging I would like to understand how best to test the library on another project so as to have a fair test before merging.

----------
This is the old data for the issue.

when we try to install the library with npm this problem comes up:

image

<br/>
<br/>

This problem was also encountered by other users since I saw that there is an [open issue here](https://github.com/anubra266/choc-autocomplete/issues/175).
Thought I'd update the "framer-motion" dependency since as of today it's up to version 10.12.10.
At the moment I have no idea how I can test this edit on my real production project, do you have any ideas?
I tried to install the local repository (forked repo) in my project (my production project) but it gave me an error.

----------

### CODE REVIEW

**Comment by huajun07** [comment]
## Testing installation

There is an [issue](https://www.github.com/npm/cli/issues/5108) with npm installing local dependencies where the peer dependencies do not get pulled in. I believe that cloning the repo and running `npm install ./choc-autocomplete` will show a successful installation, even with conflicting peer dependencies.

Hence I tested by npm installing from your fork directly. In a project with ChakraUI installed:
```bash
npm install Richi2293/choc-autocomplete#fix/framer-motion    # works fine
npm install anubra266/choc-autocomplete#main    # fails because of framer-motion peer dependency
```

## Testing the project

Build files are not pushed to GitHub, so I think the only way to test this is to install the package locally. In your local project:
```bash
git clone https://github.com/Richi2293/choc-autocomplete
cd choc-autocomplete
git checkout fix/framer-motion

yarn
yarn build

cd ../
npm install ./choc-autocomplete
```

I've tested it locally (though not extensively) and the update seems to be working fine.

**Comment by Kysluss** [comment]
I just put these changes into an active project.  Again, not extensive testing either, but it has had a few days of production use without issue.  @anubra266 would it be possible to merge this PR?

**Comment by anubra266** [comment]
@Kysluss released in [v5.1.6](https://github.com/anubra266/choc-autocomplete/releases/tag/5.1.6)

**Comment by Kysluss** [comment]
Thank you so much!  I'll update to latest version and can open a new issue if anything weird comes up.

**Pull request merged**
